name: CI Organization AbilityTecnologiaTi

on:
  workflow_call:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: CI check
        run: echo "CI obrigatório executado com sucesso"